// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Dratsi Sama",
            "url": "http://dratsisama.com",
            "email": "contact@dratsisama.com"
        },
        "license": {
            "name": "MIT License",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/interact-stand": {
            "post": {
                "description": "Permet à un utilisateur d'interagir avec un stand spécifique (nourriture, boisson, activité, etc.)",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stand"
                ],
                "summary": "Interaction avec un stand",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nom d'utilisateur",
                        "name": "username",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Type de stand (ex: 'food', 'drink', 'activity')",
                        "name": "stand",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StandInteractionResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Authentifie un utilisateur et retourne un token JWT",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentification"
                ],
                "summary": "Authentification de l'utilisateur",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nom d'utilisateur",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Rôle de l'utilisateur (ex: 'parent', 'enfant', 'organisateur')",
                        "name": "role",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.TokenResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/payment": {
            "post": {
                "description": "Traite une demande de paiement en fonction des détails fournis",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Paiement"
                ],
                "summary": "Processus de paiement",
                "parameters": [
                    {
                        "description": "Données de paiement",
                        "name": "paymentData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.PaymentResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/statistics": {
            "get": {
                "description": "Renvoie les statistiques actuelles du système",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Statistiques"
                ],
                "summary": "Récupérer les statistiques",
                "responses": {
                    "200": {
                        "description": "Statistiques actuelles",
                        "schema": {
                            "type": "object",
                            "additionalProperties": true
                        }
                    }
                }
            }
        },
        "/tokens/buy": {
            "post": {
                "description": "Permet à un utilisateur d'acheter des jetons",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jetons"
                ],
                "summary": "Achat de jetons",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nom d'utilisateur",
                        "name": "username",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Nombre de jetons à acheter",
                        "name": "amount",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BuyTokensResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tokens/distribute": {
            "post": {
                "description": "Permet à un parent de distribuer des jetons à son enfant",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jetons"
                ],
                "summary": "Distribution de jetons",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nom d'utilisateur du parent",
                        "name": "username",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Nom d'utilisateur de l'enfant",
                        "name": "child",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Nombre de jetons à distribuer",
                        "name": "amount",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DistributeTokensResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tombola/buy": {
            "post": {
                "description": "Permet à un utilisateur d'acheter un billet de tombola",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tombola"
                ],
                "summary": "Acheter un billet de tombola",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nom d'utilisateur",
                        "name": "username",
                        "in": "header",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BuyTombolaTicketResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tombola/draw": {
            "post": {
                "description": "Effectue le tirage de la tombola et retourne le gagnant",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Tombola"
                ],
                "summary": "Tirage de la tombola",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DrawTombolaResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users": {
            "post": {
                "description": "Crée un nouvel utilisateur avec le nom d'utilisateur et le rôle spécifiés",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Utilisateurs"
                ],
                "summary": "Créer un nouvel utilisateur",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nom d'utilisateur",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Rôle de l'utilisateur (ex: 'parent', 'enfant', 'organisateur')",
                        "name": "role",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.CreateUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/users/{username}": {
            "get": {
                "description": "Récupère les informations d'un utilisateur à partir de son nom d'utilisateur",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Utilisateurs"
                ],
                "summary": "Récupérer les détails d'un utilisateur",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nom d'utilisateur",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ws/chat": {
            "get": {
                "description": "Établit une connexion WebSocket pour la fonctionnalité de chat en temps réel",
                "tags": [
                    "WebSocket"
                ],
                "summary": "WebSocket Chat",
                "responses": {
                    "101": {
                        "description": "Switching Protocols\" - WebSocket handshake success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.BuyTokensResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "models.BuyTombolaTicketResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "models.CreateUserResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "models.DistributeTokensResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "models.DrawTombolaResponse": {
            "type": "object",
            "properties": {
                "winner": {
                    "type": "string"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "models.PaymentRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "Montant à payer en centimes",
                    "type": "integer"
                },
                "currency": {
                    "description": "Devise (ex: 'EUR')",
                    "type": "string"
                },
                "description": {
                    "description": "Description du paiement",
                    "type": "string"
                },
                "source": {
                    "description": "Source de paiement (ex: un token de carte)",
                    "type": "string"
                }
            }
        },
        "models.PaymentResponse": {
            "type": "object",
            "properties": {
                "chargeID": {
                    "description": "L'identifiant du paiement",
                    "type": "string"
                }
            }
        },
        "models.StandInteractionResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "models.TokenResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "models.UserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "ApiKeyAuth": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Kermisys API Documentation",
	Description:      "Documentation de l'API pour la gestion des kermesses scolaires avec fonctionnalités de stand, tombola, utilisateurs, etc.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
