// Package docs Code generated by swaggo/swag. DO NOT EDIT
package docs

import "github.com/swaggo/swag"

const docTemplate = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{escape .Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Dr_AtsiSama",
            "url": "http://dratsisama.com",
            "email": "contact@dratsisama.com"
        },
        "license": {
            "name": "MIT License",
            "url": "https://opensource.org/licenses/MIT"
        },
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/forgot-password": {
            "post": {
                "description": "Envoie un lien de réinitialisation à l'utilisateur",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentification"
                ],
                "summary": "Mot de passe oublié",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Adresse e-mail",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/kermesses": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Récupère la liste de toutes les kermesses avec pagination et filtres",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Kermesses"
                ],
                "summary": "Récupérer toutes les kermesses",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "Numéro de la page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "description": "Nombre d'éléments par page",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrer par nom de la kermesse",
                        "name": "name",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrer par localisation de la kermesse",
                        "name": "location",
                        "in": "query"
                    },
                    {
                        "type": "string",
                        "description": "Filtrer par date de début (format: YYYY-MM-DD)",
                        "name": "startDate",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Kermesse"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Crée une nouvelle kermesse avec les détails fournis",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Kermesses"
                ],
                "summary": "Créer une nouvelle kermesse",
                "parameters": [
                    {
                        "description": "Détails de la kermesse",
                        "name": "kermesse",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Kermesse"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Kermesse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/kermesses/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Récupère les détails d'une kermesse par son ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Kermesses"
                ],
                "summary": "Récupérer une kermesse par ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la kermesse",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Kermesse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Met à jour les détails d'une kermesse existante",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Kermesses"
                ],
                "summary": "Mettre à jour une kermesse",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la kermesse",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Détails mis à jour de la kermesse",
                        "name": "kermesse",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Kermesse"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Kermesse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Supprime une kermesse par son ID",
                "tags": [
                    "Kermesses"
                ],
                "summary": "Supprimer une kermesse",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la kermesse",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "No Content"
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/kermesses/{id}/participants/{user_id}": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Ajoute un utilisateur en tant que participant à une kermesse",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Kermesses"
                ],
                "summary": "Ajouter un participant à une kermesse",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la kermesse",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID de l'utilisateur",
                        "name": "user_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/kermesses/{id}/stands/{stand_id}": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Ajoute un stand à une kermesse",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Kermesses"
                ],
                "summary": "Ajouter un stand à une kermesse",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la kermesse",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "ID du stand",
                        "name": "stand_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/login": {
            "post": {
                "description": "Authentifie un utilisateur et retourne un jeton JWT",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentification"
                ],
                "summary": "Connexion",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nom d'utilisateur",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Mot de passe",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.LoginResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/logout": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Déconnexion de l'utilisateur",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentification"
                ],
                "summary": "Déconnexion",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MessageResponse"
                        }
                    }
                }
            }
        },
        "/payments": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Traite une demande de paiement en fonction des détails fournis",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Paiements"
                ],
                "summary": "Processus de paiement",
                "parameters": [
                    {
                        "description": "Données de paiement",
                        "name": "paymentData",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.PaymentRequest"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Transaction"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/payments/user/{userID}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Récupère toutes les transactions liées à un utilisateur",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Paiements"
                ],
                "summary": "Récupérer les transactions d'un utilisateur",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de l'utilisateur",
                        "name": "userID",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Transaction"
                            }
                        }
                    }
                }
            }
        },
        "/register": {
            "post": {
                "description": "Crée un nouvel utilisateur",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentification"
                ],
                "summary": "Inscription",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nom d'utilisateur",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Mot de passe",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Adresse e-mail",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Rôle de l'utilisateur",
                        "name": "role",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/reset-password": {
            "post": {
                "description": "Permet à un utilisateur de réinitialiser son mot de passe",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Authentification"
                ],
                "summary": "Réinitialiser le mot de passe",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Token de réinitialisation",
                        "name": "token",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Nouveau mot de passe",
                        "name": "newPassword",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.MessageResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/stands": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Récupère la liste de tous les stands avec pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stands"
                ],
                "summary": "Récupérer tous les stands avec pagination",
                "parameters": [
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Numéro de la page",
                        "name": "page",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 10,
                        "description": "Nombre d'éléments par page",
                        "name": "limit",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.Stand"
                            }
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Ajoute un nouveau stand",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stands"
                ],
                "summary": "Créer un stand",
                "parameters": [
                    {
                        "description": "Détails du stand (Nom, Description, etc.)",
                        "name": "stand",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Stand"
                        }
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.Stand"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/stands/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Récupère les détails d'un stand par son ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stands"
                ],
                "summary": "Récupérer un stand par ID",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID du stand",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Stand"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Met à jour les détails d'un stand existant",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Stands"
                ],
                "summary": "Mettre à jour un stand",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID du stand",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "description": "Détails du stand",
                        "name": "stand",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/models.Stand"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.Stand"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            },
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Supprime un stand par son ID",
                "tags": [
                    "Stands"
                ],
                "summary": "Supprimer un stand",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID du stand",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "204": {
                        "description": "Stand deleted",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/stands/{id}/interact": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Permet à un utilisateur d'interagir avec un stand spécifique",
                "tags": [
                    "Stands"
                ],
                "summary": "Interagir avec un stand",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID du stand",
                        "name": "id",
                        "in": "path",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Action effectuée (ex: 'buy_item', 'play_game')",
                        "name": "action",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Quantité à affecter (par défaut 1)",
                        "name": "quantity",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "Interaction réussie",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/stats/kermesse/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Récupère les statistiques de la kermesse par ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Statistiques"
                ],
                "summary": "Obtenir les statistiques de la kermesse",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la kermesse",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.KermesseStats"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/stats/organisateur/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Récupère les statistiques de l'organisateur par ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Statistiques"
                ],
                "summary": "Obtenir les statistiques de l'organisateur",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de l'organisateur",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.OrganisateurStats"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/stats/stand/{id}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Récupère les statistiques d'un stand par ID",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Statistiques"
                ],
                "summary": "Obtenir les statistiques d'un stand",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID du stand",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.StandStats"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tokens/buy": {
            "post": {
                "description": "Permet à un utilisateur d'acheter des jetons",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jetons"
                ],
                "summary": "Achat de jetons",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nom d'utilisateur",
                        "name": "username",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Nombre de jetons à acheter",
                        "name": "amount",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.BuyTokensResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/tokens/distribute": {
            "post": {
                "description": "Permet à un parent de distribuer des jetons à son enfant",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Jetons"
                ],
                "summary": "Distribution de jetons",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nom d'utilisateur du parent",
                        "name": "username",
                        "in": "header",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Nom d'utilisateur de l'enfant",
                        "name": "child",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "description": "Nombre de jetons à distribuer",
                        "name": "amount",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.DistributeTokensResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Crée un nouvel utilisateur avec le nom d'utilisateur, l'adresse e-mail, et le rôle spécifiés",
                "consumes": [
                    "application/x-www-form-urlencoded"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Utilisateurs"
                ],
                "summary": "Créer un nouvel utilisateur",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nom d'utilisateur",
                        "name": "username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Adresse e-mail",
                        "name": "email",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Rôle de l'utilisateur (ex: 'parent', 'enfant', 'organisateur')",
                        "name": "role",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Mot de passe de l'utilisateur",
                        "name": "password",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.CreateUserResponse"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/children": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Renvoie la liste de tous les enfants associés à un parent spécifique",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Parent-Enfant"
                ],
                "summary": "Liste des enfants associés à un parent",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.User"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/children/{child_id}": {
            "delete": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Permet de désassocier un enfant d'un parent et de lui réassigner le rôle par défaut \"parent\"",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Parent-Enfant"
                ],
                "summary": "Supprimer un enfant associé à un parent",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de l'enfant",
                        "name": "child_id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.User"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/parent-requests": {
            "post": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Permet de créer une nouvelle demande pour lier un parent et un enfant en utilisant leurs noms d'utilisateur",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Parent-Enfant"
                ],
                "summary": "Ajouter une demande parent-enfant",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nom d'utilisateur du parent",
                        "name": "parent_username",
                        "in": "formData",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "Nom d'utilisateur de l'enfant",
                        "name": "child_username",
                        "in": "formData",
                        "required": true
                    }
                ],
                "responses": {
                    "201": {
                        "description": "Created",
                        "schema": {
                            "$ref": "#/definitions/models.ParentChildRequest"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/parent-requests/accept/{id}": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Permet d'accepter une demande existante pour lier un parent et un enfant",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Parent-Enfant"
                ],
                "summary": "Accepter une demande parent-enfant",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la demande",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ParentChildRequest"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/parent-requests/reject/{id}": {
            "put": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Permet de refuser une demande existante pour lier un parent et un enfant",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Parent-Enfant"
                ],
                "summary": "Refuser une demande parent-enfant",
                "parameters": [
                    {
                        "type": "integer",
                        "description": "ID de la demande",
                        "name": "id",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.ParentChildRequest"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/parent-requests/requests": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Renvoie la liste de toutes les demandes en attente de traitement pour l'utilisateur connecté",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Parent-Enfant"
                ],
                "summary": "Liste des demandes parent-enfant pour l'utilisateur connecté",
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ParentChildRequest"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/user/{username}": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Récupère les informations d'un utilisateur à partir de son nom d'utilisateur",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Utilisateurs"
                ],
                "summary": "Récupérer les détails d'un utilisateur",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Nom d'utilisateur",
                        "name": "username",
                        "in": "path",
                        "required": true
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "$ref": "#/definitions/models.UserResponse"
                        }
                    },
                    "404": {
                        "description": "Not Found",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ws/history": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Récupère l'historique des messages entre deux utilisateurs, avec pagination",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "Chat"
                ],
                "summary": "Récupérer l'historique des messages",
                "parameters": [
                    {
                        "type": "string",
                        "description": "ID de l'expéditeur",
                        "name": "sender_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "string",
                        "description": "ID du destinataire",
                        "name": "receiver_id",
                        "in": "query",
                        "required": true
                    },
                    {
                        "type": "integer",
                        "default": 50,
                        "description": "Nombre de messages à récupérer",
                        "name": "limit",
                        "in": "query"
                    },
                    {
                        "type": "integer",
                        "default": 1,
                        "description": "Numéro de page",
                        "name": "page",
                        "in": "query"
                    }
                ],
                "responses": {
                    "200": {
                        "description": "OK",
                        "schema": {
                            "type": "array",
                            "items": {
                                "$ref": "#/definitions/models.ChatMessage"
                            }
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        },
        "/ws/private": {
            "get": {
                "security": [
                    {
                        "Bearer": []
                    }
                ],
                "description": "Établit une connexion WebSocket pour la discussion privée en temps réel entre un organisateur et un gérant de stand",
                "tags": [
                    "WebSocket"
                ],
                "summary": "WebSocket Chat Privé",
                "parameters": [
                    {
                        "type": "string",
                        "description": "Identifiant de l'utilisateur (ex : username)",
                        "name": "userID",
                        "in": "query",
                        "required": true
                    }
                ],
                "responses": {
                    "101": {
                        "description": "Switching Protocols\" - WebSocket handshake success",
                        "schema": {
                            "type": "string"
                        }
                    },
                    "400": {
                        "description": "Bad Request",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "401": {
                        "description": "Unauthorized",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    },
                    "500": {
                        "description": "Internal Server Error",
                        "schema": {
                            "$ref": "#/definitions/models.ErrorResponse"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "models.BuyTokensResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "models.ChatMessage": {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "receiver_id": {
                    "type": "string"
                },
                "sender_id": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                }
            }
        },
        "models.CreateUserResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "models.DistributeTokensResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "models.ErrorResponse": {
            "type": "object",
            "properties": {
                "error": {
                    "type": "string"
                }
            }
        },
        "models.Kermesse": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "description": {
                    "type": "string"
                },
                "end_date": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "location": {
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "organisateurs": {
                    "description": "Relation many-to-many avec les organisateurs",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.User"
                    }
                },
                "participants": {
                    "description": "Relation many-to-many avec les participants",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.User"
                    }
                },
                "stands": {
                    "description": "Association one-to-many avec les stands",
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/models.Stand"
                    }
                },
                "start_date": {
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.KermesseStats": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "kermesse_id": {
                    "type": "integer"
                },
                "total_participants": {
                    "type": "integer"
                },
                "total_revenue": {
                    "type": "number"
                },
                "total_tokens_used": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.LoginResponse": {
            "type": "object",
            "properties": {
                "token": {
                    "type": "string"
                }
            }
        },
        "models.MessageResponse": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "models.OrganisateurStats": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "organisateur_id": {
                    "type": "integer"
                },
                "total_kermesses": {
                    "type": "integer"
                },
                "total_revenue": {
                    "type": "number"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.ParentChildRequest": {
            "type": "object",
            "properties": {
                "child": {
                    "$ref": "#/definitions/models.User"
                },
                "child_id": {
                    "type": "integer"
                },
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "parent": {
                    "description": "Associations",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.User"
                        }
                    ]
                },
                "parent_id": {
                    "type": "integer"
                },
                "status": {
                    "description": "pending, accepted, rejected",
                    "type": "string"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.PaymentRequest": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "Montant à payer en centimes",
                    "type": "integer"
                },
                "currency": {
                    "description": "Devise (ex: 'EUR')",
                    "type": "string"
                },
                "description": {
                    "description": "Description du paiement",
                    "type": "string"
                },
                "source": {
                    "description": "Source de paiement (ex: un token de carte)",
                    "type": "string"
                }
            }
        },
        "models.Stand": {
            "type": "object",
            "properties": {
                "created_at": {
                    "description": "Date de création du stand",
                    "type": "string"
                },
                "description": {
                    "description": "Augmenté la taille pour plus de flexibilité",
                    "type": "string"
                },
                "end_date": {
                    "description": "Date de fin du stand",
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "kermesse": {
                    "description": "Associations",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Kermesse"
                        }
                    ]
                },
                "kermesse_id": {
                    "description": "Référence vers la Kermesse",
                    "type": "integer"
                },
                "location": {
                    "description": "Lieu où se trouve le stand",
                    "type": "string"
                },
                "name": {
                    "type": "string"
                },
                "owner": {
                    "$ref": "#/definitions/models.User"
                },
                "owner_id": {
                    "description": "Référence vers le User qui tient le stand",
                    "type": "integer"
                },
                "start_date": {
                    "description": "Date de début du stand",
                    "type": "string"
                },
                "stock": {
                    "type": "integer"
                },
                "type": {
                    "description": "e.g., \"food\", \"game\"",
                    "type": "string"
                },
                "updated_at": {
                    "description": "Date de la dernière mise à jour du stand",
                    "type": "string"
                }
            }
        },
        "models.StandStats": {
            "type": "object",
            "properties": {
                "created_at": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "items_sold": {
                    "type": "integer"
                },
                "revenue": {
                    "type": "number"
                },
                "stand_id": {
                    "type": "integer"
                },
                "total_tokens_used": {
                    "type": "integer"
                },
                "updated_at": {
                    "type": "string"
                }
            }
        },
        "models.Transaction": {
            "type": "object",
            "properties": {
                "amount": {
                    "description": "Nombre de jetons utilisés",
                    "type": "integer"
                },
                "currency": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "kermesseID": {
                    "type": "integer"
                },
                "paymentIntent": {
                    "type": "string"
                },
                "stand": {
                    "description": "Associations",
                    "allOf": [
                        {
                            "$ref": "#/definitions/models.Stand"
                        }
                    ]
                },
                "standID": {
                    "description": "Référence vers le stand",
                    "type": "integer"
                },
                "status": {
                    "type": "string"
                },
                "timestamp": {
                    "type": "string"
                },
                "user": {
                    "$ref": "#/definitions/models.User"
                },
                "userID": {
                    "description": "Référence vers l'utilisateur",
                    "type": "integer"
                }
            }
        },
        "models.User": {
            "type": "object",
            "properties": {
                "createdAt": {
                    "type": "string"
                },
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "passwordHash": {
                    "type": "string"
                },
                "resetToken": {
                    "description": "Token de réinitialisation",
                    "type": "string"
                },
                "resetTokenExpiry": {
                    "description": "Expiration du token de réinitialisation",
                    "type": "string"
                },
                "role": {
                    "type": "string"
                },
                "updatedAt": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        },
        "models.UserResponse": {
            "type": "object",
            "properties": {
                "email": {
                    "type": "string"
                },
                "id": {
                    "type": "integer"
                },
                "role": {
                    "type": "string"
                },
                "username": {
                    "type": "string"
                }
            }
        }
    },
    "securityDefinitions": {
        "Bearer": {
            "type": "apiKey",
            "name": "Authorization",
            "in": "header"
        }
    }
}`

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = &swag.Spec{
	Version:          "1.0",
	Host:             "localhost:8080",
	BasePath:         "/",
	Schemes:          []string{},
	Title:            "Kermisys API Documentation",
	Description:      "Documentation de l'API pour la gestion des kermesses scolaires avec fonctionnalités de stand, tombola, utilisateurs, etc.",
	InfoInstanceName: "swagger",
	SwaggerTemplate:  docTemplate,
	LeftDelim:        "{{",
	RightDelim:       "}}",
}

func init() {
	swag.Register(SwaggerInfo.InstanceName(), SwaggerInfo)
}
